### ISSUE TITLE
Beautify code

### ISSUE THREAD

**Issue by FedorLap2006** [sqdshcom/DreamBot-v2#3]
[Code begin link](https://github.com/sqdshcom/DreamBot-v2/blob/6140788f2ac66d0665b6840c8138270d4c43c61d/bot.js#L6)

May be use `Object.assign` or use `global` scope for initializing bot variables?

**Comment by yukisnowflake** [comment]
Во-первых, зачем.
Во-вторых, Федя, ты можешь писать на русском.

**Comment by FedorLap2006** [comment]
Первое - код сделать красивее и более читаемым.
Сравни сам:
```js
obj = new Object()
obj.a = 10
obj.b = "aaa"
obj.c = 10 + "100"
obj.d = "bruh"
```
против
 ```js
obj = new Object()
obj = Object.assign(obj, {
     a: 10, b: "aaa", c: 10 + "100", d: "bruh"
})
```
Второе - окей.
